// Import all actions from appwrite-actions
export {
  createSubject,
  updateSubject,
  deleteSubject,
  createClass,
  updateClass,
  deleteClass,
  createTeacher,
  updateTeacher,
  deleteTeacher,
  createStudent,
  updateStudent,
  deleteStudent,
  createParent,
  updateParent,
  deleteParent,
  createExam,
  updateExam,
  deleteExam,
  createEvent,
  updateEvent,
  deleteEvent,
  createAnnouncement,
  updateAnnouncement,
  deleteAnnouncement,
  createAttendance,
  updateAttendance,
  deleteLesson,
  deleteAssignment,
  deleteResult,
  deleteAttendance,
  getTeachersForSubject,
} from "./appwrite-actions";
