// Import all actions from appwrite-actions
export {
  createSubject,
  updateSubject,
  deleteSubject,
  createClass,
  updateClass,
  deleteClass,
  createTeacher,
  updateTeacher,
  deleteTeacher,
  createStudent,
  updateStudent,
  deleteStudent,
  createExam,
  updateExam,
  deleteExam,
  createEvent,
  updateEvent,
  deleteEvent,
  createAnnouncement,
  updateAnnouncement,
  deleteAnnouncement,
  deleteLesson,
  deleteAssignment,
  deleteResult,
  deleteAttendance,
} from "./appwrite-actions";
